### ISSUE TITLE
Index error in serverquotes.py when deleting quotes

### ISSUE THREAD

**Issue by Yandols** [calebj/calebj-cogs#12]
I tried your serverquotes.py today, everything worked fine until I tried to delete a quote my members added when they used the command incorrectly.

Apparently's there's an index error when trying to remove quotes, shown in screenshots below:
![image](https://cloud.githubusercontent.com/assets/2742965/20716374/f7ed450e-b68c-11e6-9ce5-9e6ad787e4e3.png)
![image](https://cloud.githubusercontent.com/assets/2742965/20716379/fab0b9ec-b68c-11e6-9aa3-fe77fa84933f.png)

Note: `!dq` is a alias I made that shortens `!rmquote`

**Comment by calebj** [comment]
Should be fixed in ec5a6b451365e49403939b0f97caf2ae25a68d61
