### ISSUE TITLE
Where do I see log data from activity log?

### ISSUE THREAD

**Issue by sean-james** [calebj/calebj-cogs#14]

**Comment by skeith** [comment]
If you are the owner of the bot and the maintainer of the server / machine the bot is hosted, it's inside data/activitylogger/server id/

**Comment by calebj** [comment]
Yukirin is correct. Message logs are stored in
`data/activitylog/(serverid)/(channelid).log`
and attachments are in
`data/activitylog/(serverid)/(channelid)_attachments/(attachmentid)_filename`
