### ISSUE TITLE
Double cooldowns in Duels

### ISSUE THREAD

**Issue by CRASNY** [calebj/calebj-cogs#18]
Without modifying any code, I'm getting two cooldown messages on cooldown. Any idea how to work around that?

> [1:13 PM] Liz: >duel David
> [1:13 PM] BOTFSY: You are on cooldown. Try again in 8.12s
> [1:13 PM] BOTFSY: This command is on cooldown. Try again in 8.12 seconds.

**Comment by calebj** [comment]
That looks like a Red issue; I know the cooldown messages were added somewhat recently. See if it happens in another cog with cooldowns.

**Comment by CRASNY** [comment]
Thanks for the really fast reply. Maybe you can help me understand cooldowns actually, since I haven't found that in documentation.

`    @commands.cooldown(1, 60, commands.BucketType.user)`
I know the 60 represents a minute cooldown, but what is the 1? If I change that to 2, it will allow 2 per 60 seconds, or?

**Comment by calebj** [comment]
It's pretty easy to grok from the cooldown code inside the library at https://github.com/Rapptz/discord.py/blob/async/discord/ext/commands/cooldowns.py .
In this case, it is a limit of use per minute per user. The buckets can also be per channel, server, or global.
EDIT: for some stupid reason, email replies don't support markdown.

**Comment by CRASNY** [comment]
Thanks for the help. I managed to fix this by commenting out this line in red.py:
```
            #await bot.send_message(channel, error)
            await bot.send_message(channel, "This command is on cooldown. "
                                            "Try again in {:.2f} seconds."
                                            "".format(error.retry_after))
```

I'm not sure why it was performing both of these sends, and not entirely sure of the consequences to other cogs in commenting that out, but at least Duels works better now.

One more unrelated question though, I'm noticing after the fifth message that's sent it's as if the bot gets throttled and it pauses for a moment before continuing to output duel results. Do you know why that is?

**Comment by calebj** [comment]
That looks like a modified version of red.py; [the mainline version](https://github.com/Twentysix26/Red-DiscordBot/blob/develop/red.py#L375) doesn't have two `send_message`s.

In any case, this is a Red issue and not with my cogs specifically. I think you should `git reset` your red.py to match the maintained version, or more things are bound to break.
