### ISSUE TITLE
[duel] Economy integration

### ISSUE THREAD

**Issue by calebj** [calebj/calebj-cogs#24]
Ideas proposed:
- [x] Purchasable protection
- ~~Periodic prizes for being in the top of the leaderboard~~
- ~~Purchasable HP upgrades and other powerups~~

**Comment by Jonny0181** [comment]
I'm suggesting maybe a embed toggle were it has 3 fields. This embed toggle would probably only be suitable if the edit mode is enabled but, maybe 2 fields on top where it has P1 and P2 health (Maybe like this 59/100) and after every action happens the users health goes down. Here is a screenshot of maybe some sort of template or something you can base it off of.
![image](https://cloud.githubusercontent.com/assets/22266893/24770690/780e4a1a-1ad0-11e7-87c6-1fe2a060509d.png)

**Comment by skeith** [comment]
Bump for embed. This way the battle flow will not be disrupted by chat

**Comment by addep** [comment]
each user gets an embed character and able to purchase upgrades and moves with economy. not randomized fights but 'pokemon-esque'.
if possible, make buttons for abilites with emotes so the user dont have to write. just click the corresponding emote.

**Comment by calebj** [comment]
@addep I don't think I want to maintain anything more complex than a random system. I don't think I'll even be doing purchasable upgrades. As I mentioned in my channel the other day, full-fledged PvP is outside the scope of this cog. I might consider a commission for it, though.
