### ISSUE TITLE
Suggestion for activitylog

### ISSUE THREAD

**Issue by AriRexouium** [calebj/calebj-cogs#36]
There should be a setting so that everything is printed to the console too.

**Comment by skeith** [comment]
Oh no,
While this might work on small server, on a big server, the console will be flooded

**Comment by AriRexouium** [comment]
I should've made it more specific. 😄 It would be used for smaller servers.

**Comment by AriRexouium** [comment]
Plus, it should be able to be toggled so it's up to the bot owner if they want it enabled or not.

**Comment by calebj** [comment]
If you're on Linux or OSX, you already have the `tail -f` command. There are windows ports of the program as well. Can you look into that and see if it does what you want?

**Comment by AriRexouium** [comment]
I am not on Linux or OSX.
Edit: Nvm, I noticed the Windows ports.

**Comment by calebj** [comment]
Check http://tailforwin32.sourceforge.net/ ?

**Comment by AriRexouium** [comment]
This is exactly what I wanted. Thank you!

**Comment by calebj** [comment]
Alright. Closing this now~

**Comment by AriRexouium** [comment]
Sorry to bother you again..
What I meant by this is I want to be able to moderate a server's channels in one place without having to switch channels all the time.
That doesn't help much since I still have switch which file i'm viewing.

**Comment by calebj** [comment]
Simple: just specify multiple files, or a wildcard.
`tail -f data\activitylogger\<serverid>\*.log`

**Comment by AriRexouium** [comment]
But i'm not on a Linux machine, i'm using Windows.
Not sure how i'd be able to execute that from CMD.

**Comment by calebj** [comment]
If you use MINGW/Cygwin tail, those will be available for you to run via the terminal. And I'm fairly certain tailforwin32 supports multiple open files.

**Comment by AriRexouium** [comment]
It kind of goes nuts in console because of the refresh rate.
[Here's what I mean.](http://i.imgur.com/t7jbDuB.gifv)
This makes it rather hard to keep up with the chat. It works best on a single channel, but on multiple channels it just refreshes like crazy.

All I want to do is see the chat from all channels live kind of like what you would see a server console.

**Comment by skeith** [comment]
no such feature
