### ISSUE TITLE
[Suggestion] Update dice functions

### ISSUE THREAD

**Issue by vaxjedi** [calebj/calebj-cogs#39]
Any way to convince you to use your rewrite of the dice python library in this cog? I'd love to use those more advanced options (esp. fudge dice).

**Comment by calebj** [comment]
Certainly. You can `pip install` my forked version to either the bot's `lib/` or to your user, and it'll function as a drop-in replacement. If the mainline version has already been installed to `lib/dice/`, it's a straightforward matter to replace that version with mine.

**Comment by calebj** [comment]
I'm making an effort to whip my changes into shape. There's not much left to finish, so stay tuned :3

**Comment by calebj** [comment]
Although I was made a co-maintainer of the upstream dice project a while back and my changes have been merged, I'm sitting on another set of changes for both the library and the cog. I'll leave this open until those are done.
