### ISSUE TITLE
Duels issue or need more explanation on usage

### ISSUE THREAD

**Issue by skeith** [calebj/calebj-cogs#4]
Specific to `[p]duels` which give us

```
[p]duels [top=10]

Shows the duel leaderboard, defaults to top 10
```

But somehow I can't figure out the right command and parameter. I have tried

```
[p]duels 10
[p]duels top: 10
[p]duels top=10
```

The first one gave `Error in command 'duels' - AttributeError: 'NoneType' object has no attribute 'nick'` while the latter just output the help info again

**Comment by calebj** [comment]
Fixed in d9d746f82ce24d55715f8d89ed71eb33fed64cfe
