### ISSUE TITLE
Make individual logs for each channel

### ISSUE THREAD

**Issue by DannyB5544** [calebj/calebj-cogs#40]
Currently, it's a nightmare for me to sort through the logs, looking for some subtle detail or who the hell mentioned me for the lols. I was thinking could there be a system where each channel has its own log, and They are stored in a singular folder for that server?

**Comment by DannyB5544** [comment]
For ActivityLog, of course. Lol.

**Comment by skeith** [comment]
It’s saved individually per channel

**Comment by DannyB5544** [comment]
Huh. I must be using the wrong one then. One sec...

*Goes and checks*
Oh fml, I've got my repo's named wrong rip. My bad!
