### ISSUE TITLE
ReCensor enhancements

### ISSUE THREAD

**Issue by calebj** [calebj/calebj-cogs#43]
#42 gave me some feature ideas:

- [x] Check edited messages (requested by @TheFinestSurgeon)
- [x] Code modernization (wtf even is an enum?)
- [x] Check message sequence (also requested by @TheFinestSurgeon, moved from #46)
- [x] Extend regex to check for attachment presence/type (req. by ~~@dannymichel~~ @chnaski, moved from #47)
- [x] Pattern testing mode
- [x] Filter immunity role(s)
- [x] Search/match toggle
- Sanity checks on patterns when adding:
  - ~~Matches everything?~~
  - ~~Won't ever match anything? (Is this even possible?)~~
  - ~~Slow/unoptimized pattern?~~
- [x] Pattern library

**Comment by skeith** [comment]
May I add?

Please make recensor have built in commonly used pattern, such as discord invites, common swear words (as example pattern),

**Comment by calebj** [comment]
For the swear words, that's probably better suited to a set-based match, which isn't in the scope of the cog. Nonetheless, if/when I add a "pattern library", people are welcome to PR helpful entries such as those.

**Comment by skeith** [comment]
would it be inefficient if recensor were to use json file for the filtered words and you just invoke it with command + arguments whether it's case sensitive, as is or part of sentence etc?

**Comment by calebj** [comment]
A regex for a word list would be pretty inefficient. I'd spin this idea into a separate cog, or extend an existing one.

**Comment by TheFinestSurgeon** [comment]
Another enchantment could be filtering edited messages. Currently users can bypass the filter by sending a message then editing in filtered word(s) EX: https://i.imgur.com/Vku79wQ.gifv

**Comment by calebj** [comment]
I'll work on message sequences in the next release; what are some example use cases of attachment filtering?

**Comment by calebj** [comment]
[This](https://regex101.com/r/Now1d6/1) is an example of what it could look like. Thoughts?

**Comment by skeith** [comment]
K.

JK, don't kill me.
Is there a way to apply recensor to the attachment name?

**Comment by calebj** [comment]
What do you mean? The first line has a regex for a filename matching `.*\.(?:png|jpg|jpeg|gif|pdf)`. It doesn't make much sense to look at anything *except* the attachment name.

**Comment by skeith** [comment]
yeah, that's what I mean, I missed it

**Comment by calebj** [comment]
@dannymichel do you want to give this a shot? I just added the attachment stuff. See [this regex101 page](https://regex101.com/r/Now1d6/2) for some simple examples.

**Comment by chnaski** [comment]
I'll try it now.
I'm dannymichel
