### ISSUE TITLE
Regex Issue

### ISSUE THREAD

**Issue by dannymichel** [calebj/calebj-cogs#47]
Hey guys, for a while now, i've been using regex to disallow text in my media channels such as #selfies, and it's been great, but one annoyance is it doesn't allow any text what-so-ever which means people cant add captions to uploads. The full regex is 
```
#selfie
excl | ^$
incl | ^([a-zA-Z0-9-]+\.)+(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+
```
Any ideas? Any help would be greatly appreciated

**Comment by calebj** [comment]
Moving this to #43; subscribe there for updates.
