### ISSUE TITLE
Add use voice activation permissions to disabled to punished user

### ISSUE THREAD

**Issue by Bartixxx32** [calebj/calebj-cogs#49]
#Hello i discovered a  bug.
When user is punished and have enabled voice activation he can talk
way to fix it is disable permissions for that
I fixed it myself and hope to help you or others fixed too
To fix it need:
add "perms.use_voice_activation = False" under permissions gived to user when punishing
https://github.com/calebj/calebj-cogs/compare/master...Bartixxx32:patch-1

**Comment by calebj** [comment]
I think that instead of this, it would be best to toggle server mute on the affected user. I don't think the defaults should be changed, because telling the user that they were muted because of VAD is misleading.

**Comment by Bartixxx32** [comment]
Yes but anyway without this all on my server can talk only uaing voice activation key bind didnt work (i fixed code) but need make it every update

**Comment by calebj** [comment]
I just pushed punish v1.8.0, which has proper server voice mute, to the develop branch. Could you try it out and report back?
