### ISSUE TITLE
Suggestions for Duel cog

### ISSUE THREAD

**Issue by Mamalus** [calebj/calebj-cogs#5]
Here's some suggestion that you might implement
1. Purchase a protection using the economy bank.
Customizable purchase and time.
2. Cooldown on duel (don't know if it's there not on my computer)
3. Leaderboard prize each week.
I'll think of more if I can

**Comment by calebj** [comment]
The duel command already has a limit of two calls per minute per user. 
Another idea I just had: add a limit such that only one duel can be underway at a time.

**Comment by Mamalus** [comment]
Another Idea if they are protected they can't attack if they do they will lose the protections

**Comment by calebj** [comment]
I made it so you can't attack at all if you're on the protection list in c9f3cdb9220a2f9cacc9e97b6b9e4f5e7f7fe2d2.

I'm working on making protection purchasable, self-assigned or mod-only. The setting will be up to the bot admins.

**Comment by Mamalus** [comment]
Adding a shop?
Purchasable Hp
Stats Reset?

**Comment by Mamalus** [comment]
Also damage

**Comment by lakai** [comment]
Can dual kick or ban the loser?

**Comment by calebj** [comment]
Nah, it's just meant to be a fun game. There is a `duel_completion` event fired after each duel; you can write a cog to listen to this event and react however you want.

**Comment by skeith** [comment]
- [x] Duelist leaderboard reset command (keeping protected list intact)
- [ ] Economy integration (credit bonus on most win per week/month (settable) also integrated with reset command above, like auto reset per week/month

**Comment by Jonny0181** [comment]
Maybe make it so there is a per-server toggle for the duel game to edit the message and add on with the actions instead of sending a new message ever action.

**Comment by calebj** [comment]
@JonnyBoy2000 added edit mode in 834a12fc0574c5fa3069447d2bd8524734648be9

**Comment by calebj** [comment]
@skeith and @Mamalus I'm moving economy integration to a separate, more specific issue, since the smaller ideas have been implemented already. #24
