### ISSUE TITLE
[embedwiz] ; in embed content does not work (too many fields)

### ISSUE THREAD

**Issue by Mystard** [calebj/calebj-cogs#58]
When the content "field" has the ; character the embed will not be created because of
"Invalid specification: got too many fields (8, expected 7)" error.

This is obviously because ; is the separator of the different fields, but probably not intended behavior.
(+ I need it 😄)

![12-06-2018_01-55-02](https://user-images.githubusercontent.com/28576956/41261488-955ad634-6de4-11e8-87f4-36732cc8e10f.png)

**Comment by calebj** [comment]
Fixed in a287e46538a28065dbddec24041be5ab6d0458e9
