### ISSUE TITLE
Duel protection bug

### ISSUE THREAD

**Issue by OrdinatorStouff** [calebj/calebj-cogs#6]
I found a bug in duel.py when a user is given protection, the !duels leaderboard fails to display. The problem seems to be due to the fact that "protection" is added to the config json at the same level as other users' stats. When the duels command tried to parse all users' stats it fails because "protection" is not a valid user ID.  

Other suggestions:  
Protected users are not allowed to initiate a duel--that's the price they pay.
Protected users do not get a "free" win when someone else duels them
Other users do not get an unfair "loss" when dueling a protected user (or maybe give a "confirmation" to ask if they're sure they want to duel someone that's under protection)

I hacked in these changes/fixes and also added many more procedurally generated movesets and made the damage done affected by a slight random variation but I don't know how to use git or initiate a pull request properly (plus I'm new with python and know for a fact my changes are inefficient and not the best way to handle things)

**Comment by calebj** [comment]
I implemented the fix for the first problem in d9d746f82ce24d55715f8d89ed71eb33fed64cfe, and changed the behavior of duel when either you or the target are on the protection list in c9f3cdb9220a2f9cacc9e97b6b9e4f5e7f7fe2d2.

You can just email me the new movesets and tweaks, I'll be glad to put them in.

**Comment by OrdinatorStouff** [comment]
Here's a pastebin of my whole modified duel.py: [http://pastebin.com/dyiSVdak](http://pastebin.com/dyiSVdak)

Line 505 is where I add a little random variation in the dmg/healing done. I had it at 50% to 150% but it seemed too wide of a range. 66% through 133% seems to work better but there might be an even better way of doing that in the first place (if you even want to implement it). I just like that Move X doesn't always do Y damage every time, it does 'around' Y damage.

The other moveset statics at the beginning work well; some are silly but overall they're good save for one or two where the grammar might not work perfectly in the final string but I haven't paid attention enough to see which ones exactly.

Thanks for the cog in the first place though, it's been a lot of fun so far.

**Comment by calebj** [comment]
I'm working on integrating your suggestions, but the initial issue has been fixed.
