### ISSUE TITLE
[punish] Workaround for allow overrides

### ISSUE THREAD

**Issue by calebj** [calebj/calebj-cogs#63]
I'll post any progress I make towards getting Punish working with role or user-level overrides here. It'll _probably_  be some combination of caching former permissione and role copying.

**Comment by brandons209** [comment]
I was having the same issue in my server. I modified the punish code with a new command to for the user to store a list of roles that should be removed when punished. When a user is punished, their roles are checked against the defined list of roles. If the user has any roles that are specified to be removed, they are removed. These removed roles are then saved with the punish information. When the punish is lifted automatically or by a user, it restores all roles. I can leave the code here or submit a pull request. For parsing roles, I used some of the code from the Admin cog.

**Comment by calebj** [comment]
Those modifications are certainly welcome, and it sounds like a viable solution. Feel free to open a PR!
