### ISSUE TITLE
captcha cog issye

### ISSUE THREAD

**Issue by NoNotNick** [calebj/calebj-cogs#65]
Whenever i run [P]captchaset role-mode i get this issue in my console
`  File "C:\Users\rexal\Desktop\stuff\scripts\gits\Red-DiscordBot\cogs\captcha.py", line 954, in captchaset_role_mode
    if role_mode.lower().startswith('unverified'):
AttributeError: 'NoneType' object has no attribute 'lower'`

**Comment by calebj** [comment]
This was fixed 18 days ago in 0666b2888e60d4feb7c17e477ecedad76eac7283; please update your cogs.
