### ISSUE TITLE
[captcha] Double challenge, then kick

### ISSUE THREAD

**Issue by NoNotNick** [calebj/calebj-cogs#66]
It sends the message twice and if the user completes one the bot detects the he hasn't done the captcha and kicks them

**Comment by calebj** [comment]
Please include a list of specific and repeatable steps that cause the issue.

**Comment by NoNotNick** [comment]
Well it really doesnt send anything to my console but it makes two challenges and then it kicks the user. I reinstalled and etc. But it still does it. I set it up and made the role "unverified" And its under the plain captcha challenge. https://i.imgur.com/xTXSxPQ.png

**Comment by calebj** [comment]
What _specific_  actions reproduce the behavior? Are you manually challenging the user, or does it happen upon joining?

**Comment by NoNotNick** [comment]
it happens upon joining

**Comment by calebj** [comment]
Do you have another cog or bot that adds the unverified role to new members?

**Comment by NoNotNick** [comment]
Nope, i have autorole but thats unloaded

**Comment by calebj** [comment]
Can you give [this update](https://github.com/calebj/calebj-cogs/files/2683211/captcha.tar.gz) a shot? You'll have to unpack it, since GitHub doesn't let me upload Python files directly.

**Comment by NoNotNick** [comment]
yeah sure

**Comment by NoNotNick** [comment]
alright that fixed it thanks alot man
