### ISSUE TITLE
[xorole] Suggestion: Auto deleting with xorole commands.

### ISSUE THREAD

**Issue by Overlordmittenz** [calebj/calebj-cogs#69]
I'm currently revamping my bots and the biggest suggestion from my moderators/admins is a request for xorole to auto delete the bot's messages, and the users command.

**Comment by calebj** [comment]
I'm working on the autodelete feature now, but what do you mean by the "users command"?

**Comment by Overlordmittenz** [comment]
I think it might be a user error, because I swear it's been added. But deleting the user's command. "!xorole XYZ" after the roles have been switched.

**Comment by calebj** [comment]
Ah, I see. I read it as a reference to a command named `users`. Red does has a global deletedelay feature, but xorole doesn't have it yet.
