### ISSUE TITLE
No cogs show up 

### ISSUE THREAD

**Issue by ghost** [calebj/calebj-cogs#79]
![image](https://user-images.githubusercontent.com/16860411/113670319-9383d880-967a-11eb-8196-5613947cabe7.png)

**Comment by TwinDragon** [comment]
This repository is for Red v2 which is long dead due to Discord killing various APIs. Some of the cogs may have v3 equivalents, you can look at the [Red Index](https://index.discord.red) and see.

**Comment by calebj** [comment]
@TwinDragon is correct, this repo hasn't been updated for V3 yet. Sorry for the inconvenience.
