### ISSUE TITLE
Can't find any cogs (Red V3)

### ISSUE THREAD

**Issue by FischiTheDev** [calebj/calebj-cogs#80]
I have a little problem when installing your cogs, do you know what I'm doing wrong?

The command I try do is:
`%cog install caleb-jcogs description`

This is what I'm getting from it:
`Couldn't find this cog in calebj-cogs: description`

I have added the repo 2 days ago so I don't think anything is outdated, any help would be appreciated!

**Comment by JeffJrShim** [comment]
This repo is for Red V2. I don't think any cogs would work here if no one ports them to Red V3.

**Comment by FischiTheDev** [comment]
Oh ok, thanks!

**Comment by dannymichel** [comment]
Caleb, you're my hero. Please come back and convert recensor to v3

**Comment by Wayrion** [comment]
Pretty sure Caleb has been busy irl. You can accomplish the same results with retrigger from trusty

**Comment by dannymichel** [comment]
> Pretty sure Caleb has been busy irl. You can accomplish the same results with retrigger from trusty

Thank you, but that's actually incorrect. Trust me, I've looked into it. Myself a 3 other coders have looked into the fact that retrigger cannot do what recensor does

**Comment by Apoo711** [comment]
Hi, from what I understand Recensor just filters messages for which you can use Warden or Core's Filter I believe.

**Comment by dannymichel** [comment]
> Hi, from what I understand Recensor just filters messages for which you can use Warden or Core's Filter I believe.

Oh no my friend recensor does way way way more than that
It's the most powerful cog I've ever used
